### ISSUE TITLE
[REQUEST] ModTools

### ISSUE THREAD

**Issue by Kjewn** [Just-Some-Bots/ModTools#25]
Hey there! 

Can i get help on a few complications im running into:
- Blacklist thats currently only working globally instead of channelbased.
  Is this allready possible? otherwise i would love to request that for in the future.
- !!slowmode is currently not working in our discord. not sure if we are using the command right because it's not in the ModTools. are we doing anything wrong or is the slowmode function not implemented yet?

I hope to see my "problems" answered asap :+1: 

Thanks for your help in advance!

Koen

**Comment by MattBSG** [comment]
The repo is not supposed to be run , and is only used as a reference. As for the blacklist, I have no idea what your talking about. There is not a blacklist with the bot (only for blacklisting servers or globally banning user ids).

slowmode _does_ work. See this: https://github.com/Just-Some-Bots/ModTools/blob/master/automod/bot.py#L1049
