### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by kylek2020** [Just-Some-Bots/ModTools#35]
Hello, so I created my bot yesterday and figured out most things, but I am wondering how to let other people adjust the volume. I figured out how to let them play songs, but not this please help. Thank you in advance.

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions

**Comment by arunesh90** [comment]
I also just noticed you posted this at the wrong repo.....
