### ISSUE TITLE
Blacklist command

### ISSUE THREAD

**Issue by sirioth** [Just-Some-Bots/ModTools#38]
I'm not able to make it works i already tried everything

**Comment by BrennanFlory** [comment]
then your either not doing it right or you fucked up the code

**Comment by MattBSG** [comment]
If your running this yourself, your SOL, if you don't know how to use blacklist, then here is the bots explanation:

Usage: !!blacklist [ + | - | add | remove | clear] ["string"] ["reason"]
Adds or removes the specified word / words (string) to the blacklist!
Example: `!!blacklist + "hello"` will blacklist the word hello
