### ISSUE TITLE
[Stability] Constantly crashing/offline, wont register.

### ISSUE THREAD

**Issue by NNickey** [Just-Some-Bots/ModTools#41]
Gave the bot every single permission, and saw the bot post the 'join' message once I invited it
Said !!register, nothing happened
Went to Rh1n0-help on discord, and !!ping, no response..

Bot is heavily non functional/unstable.

**Comment by Yeehawlerz101** [comment]
For me I have it so the bot role is just under the baby admin in my discord. So that the bat has power over everyone lower than itself.

**Comment by arunesh90** [comment]
Closing as the issue as the bot was down at the time this issue was created and was also the cause of the issue.
