### ISSUE TITLE
Issues with auto summon and playing music

### ISSUE THREAD

**Issue by McLovin157** [Just-Some-Bots/ModTools#42]
The bot struggled to auto connect to the channel though after 3 or 4 attempts it finally made it to the discord channel. Though now the bot wont play music and the songs that are in que are being trashed and the songs that are being added to the que are eating its position and still not playing.

**Comment by kitapocalypse** [comment]
I am also having this problem. Also after restarting the bottom again to try and fix the issue it won't connect at all.

**Comment by MattBSG** [comment]
Wrong bot. https://github.com/Just-Some-Bots/MusicBot/wiki
