### ISSUE TITLE
python setup.py egg_info error

### ISSUE THREAD

**Issue by tarqs** [Just-Some-Bots/ModTools#45]
Hi I'm having problems installing the discord MusicBot 
There seems to be a problem when trying to install on Raspbian RPi.

when running
sudo -H pip3.5 install --upgrade -r requirements.txt
it gives cffi-markers sys_platform == win32 
doesn't match your platform.

It continues the install with cached versions and finally fails with the message:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o0ju21wx/PyNaCl/

Could you help me getting this working?

Thanks in advance!

**Comment by jaydenkieran** [comment]
This is the wrong repository. Try: https://github.com/Just-Some-Bots/MusicBot
