### ISSUE TITLE
How to run with command prompt open

### ISSUE THREAD

**Issue by Awesomeest123yt** [Just-Some-Bots/ModTools#46]
I want to run this without command prompt open, How would I do that. Or can I not.

**Comment by TheEvilSocks** [comment]
no

**Comment by arunesh90** [comment]
1. We don't give any support for running the ModTools bot, It's supposed to be only ran by SexualRhinoceros. The code is posted online as a example and for people who want to just check it out.
2. If you are talking about MusicBot, you're in the wrong ~~neighbourhood~~ [repo](https://github.com/Just-Some-Bots/MusicBot)

**Comment by ImthePeach** [comment]
On a side note with the MusicBot too, we don't help with modification of the bots code. Also you can't run a bot without something running it well, running. How else would it run if whatever's running it isn't running? That would just be run...ception
