### ISSUE TITLE
!play error

### ISSUE THREAD

**Issue by Yapperyapps** [Just-Some-Bots/ModTools#47]
The command worked yesterday but for songs it gives me this
https://hastebin.com/odorabapas.sql
And works for my videos IDK why.

Also this is running on my rasberry pi 3 It worked fine yesterday and the month I have used it but now it gives that error nothing has changed.

**Comment by jaydenkieran** [comment]
You have posted in the wrong repo.

https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
