### ISSUE TITLE
!!serverlog not sending a DM

### ISSUE THREAD

**Issue by Noremon** [Just-Some-Bots/ModTools#55]
Using the !!serverlog command does not send a DM. A user on the official RH1N0 help Server confirms it isn't working for them there either.

**Comment by MattBSG** [comment]
The only time the bot ever DMs you is during registration. I don't know who told you that, but its completely incorrect. The **correct** usage is:
```
!!serverlog set #channel
!!serverlog true
```

**Comment by Noremon** [comment]
It's listed on the command page

"!!serverinfo

 Private messages the sender all the info of the server it was used on."

**Comment by Noremon** [comment]
And I see I mixed-up the 2 Server command s D:

**Comment by Noremon** [comment]
But, yeah the !! serverinfo command doesn't send a DM

**Comment by MattBSG** [comment]
serverlog and serverinfo are very different, correct. Currently, serverinfo and some other commands are disabled because of instability issues, sorry about that.

**Comment by Noremon** [comment]
Okay, no worries! Wintery & I on the help Server were just wondering why it wasn't working is all
