### ISSUE TITLE
Playlist Emptying Because of Errors

### ISSUE THREAD

**Issue by HydraHeadhunter** [Just-Some-Bots/ModTools#57]
I've got a playlist of 150 some songs, and because of repeated occurrence of this exact error:

"
# Entry removed Tue Feb 26 17:55:26 2019
# Reason: ERROR: Signature extraction failed: Traceback (most recent call last):
#            File "C:\Users\repoo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1191, in _decrypt_signature
#              video_id, player_url, s
#            File "C:\Users\repoo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1102, in _extract_signature_function
#              res = self._parse_sig_js(code)
#            File "C:\Users\repoo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1163, in _parse_sig_js
#              jscode, 'Initial JS player signature function name', group='sig')
#            File "C:\Users\repoo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 794, in _search_regex
#              raise RegexNotFoundError('Unable to extract %s' % _name)
#          youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name
#           (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name',))
https://www.youtube.com/watch?v=_ct-IYETA7g

################################
"

That list is down to twenty.

**Comment by TheerapakG** [comment]
Run update.bat

**Comment by HydraHeadhunter** [comment]
That fixed it (it was doing this occasionally so I didn't think it'd be a version issue to update away # tech-illiterate).

If I did post this in the wrong spot, I'm sorry: It's been a hot minute since I last used it, and it's totally possible this isn't the exact bot I'm using. # SorryForTheInconvienceAndThankYouForHelpingAnyway.

**Comment by TheerapakG** [comment]
No problem. Btw the MusicBot repo is [Just-Some-Bots/MusicBot](https://github.com/Just-Some-Bots/MusicBot).
